let demo=document.getElementById("demo")
demo.classList.add("active")
let demo1=document.getElementById("demo1")
demo1.classList.add("active1")
let demo2=document.getElementById("demo2")
demo2.classList.add("active2")
let demo5=document.getElementById("demo5")
demo5.classList.add("active2")
let demo6=document.getElementById("demo6")
demo6.classList.add("active2")
let demo7=document.getElementById("demo7")
demo7.classList.add("active2")
let demo8=document.getElementById("demo8")
demo8.classList.add("active2")
let demo9=document.getElementById("demo9")
demo9.classList.add("active2")
let demo10=document.getElementById("demo10")
demo10.classList.add("active2")
let demo3=document.getElementById("demo3")
demo3.classList.add("active3")
let demo4=document.getElementById("demo4")
demo4.classList.add("active4")
let demo11=document.getElementById("demo11")
demo11.classList.add("active5")
let demo12=document.getElementById("demo12")
demo12.classList.add("active5")
let demo13=document.getElementById("demo13")
demo13.classList.add("active6")
let demo14=document.getElementById("demo14")
demo14.classList.add("active7")
let demo15=document.getElementById("demo15")
demo15.classList.add("active8")
let demo16=document.getElementById("demo16")
demo16.classList.add("active5")
let demo17=document.getElementById("demo17")
demo17.classList.add("active5")
let demo18=document.getElementById("demo18")
demo18.classList.add("active9")
let demo19=document.getElementById("demo19")
demo19.classList.add("active10")
let demo20=document.getElementById("demo20")
demo20.classList.add("active11")
let demo21=document.getElementById("demo21")
demo21.classList.add("active12")
let demo22=document.getElementById("demo22")
demo22.classList.add("active13")
let demo23=document.getElementById("demo23")
demo23.classList.add("active14")
let demo24=document.getElementById("demo24")
demo24.classList.add("active15")
let demo25=document.getElementById("demo25")
demo25.classList.add("active15")
let demo26=document.getElementById("demo26")
demo26.classList.add("active15")
let demo27=document.getElementById("demo27")
demo27.classList.add("active15")
let demo28=document.getElementById("demo28")
demo28.classList.add("active16")
let demo29=document.getElementById("demo29")
demo29.classList.add("active17")
let demo30=document.getElementById("demo30")
demo30.classList.add("active18")
let demo31=document.getElementById("demo31")
demo31.classList.add("active19")
let demo32=document.getElementById("demo32")
demo32.classList.add("active20")
let demo33=document.getElementById("demo33")
demo33.classList.add("active21")






